const ObjectsToCsv = require("objects-to-csv");

const users = [
  "post@thorgekrieger.com",
  "jonas@northasg.de",
  "ian@jorcani.com",
  "mario@funbox.es",
  "danijimenez@jorcani.onmicrosoft.com",
  "mm74@orange.fr",
  "office@multigliss.com",
  "jc.solau@orange.fr",
  "julian@artibus.fr",
  "Dennis@northasg.com",
  "martijn@northasg.com",
  "massimo.m@northkb-mystic.it",
  "jimmymazzanti@me.com",
  "marco.m@northkb-mystic.it",
  "scalabrin1@icloud.com",
  "ods@onedesign.gr",
  "akylas@onedesign.gr",
  "nik@watersportsworld.co.uk",
  "scott@watersportsworld.co.uk",
  "marketing@watersportsworld.co.uk",
  "joe@watersportsworld.co.uk ",
  "piotr@hydrosfera.pl",
  "jonas@boardsports.lt",
  "antanas@boardsports.lt",
  "IZANOS@ME.COM",
  "info@infinitysport.net",
  "martina.pavlin1@gmail.com",
  "morchev@gmail.com",
  "info@mysticstore.cz",
  "fsevcik@autrange.cz",
  "stefan.popprath@windandsnow.ch",
  "a.marton@hotmail.com",
  "matt@northasg.com",
  "salesusa@northasg.com",
  "shaun@northasg.com",
  "mike.d@northasg.com",
  "northkiteboarding.ve@gmail.com",
  "Alessandro.Allori.kb@gmail.com",
  "shopmyallisone@gmail.com",
  "grant@northkb.co.za",
  "donovan@northkb.co.za",
  "sales@barvan-int.com",
  "info@barvan-int.com",
  "nicowsf@yahoo.com.tw",
  "info@sourcekiteboarding.com",
  "bjorn@kiteboardingasia.com",
  "yavuz@kiteacademy.com",
  "sedat@kiteacademy.com ",
  "Mostafa@dukite.com ",
  "jaloulangeree@hotmail.com ",
  "nickpjacobsen@gmail.com",
  "marcjacobskite@gmail.com ",
  "j.r@jesserichman.com ",
  "innafrica@gmail.com ",
  "Camillecamkite@gmail.com",
  "bruna.kajiya@gmail.com",
  "tombridgekite1@gmail.com ",
  "info@ckperformanceclinics.co.uk",
  "annelies@northasg.com",
  "sales2@northasg.com",
  "marguerite@northasg.com",
  "sales@northasg.com",
  "jorden@northasg.com",
  "esperanza@northasg.com",
  "robert@northasg.com",
  "invoicing@northasg.com",
  "mireille@northasg.com",
  "jacqueline@northasg.com",
  "corrien@northasg.com",
  "peet@northasg.com",
  "marjo@northasg.com",
  "jose@northasg.com",
  "sander@northasg.com",
  "lieke@northasg.com",
  "edwin@northasg.com",
  "joost@northasg.com",
  "timon@northasg.com",
  "femke@northasg.com",
  "madelene@northasg.com",
  "annabel@northasg.com",
  "holley.butler@northkb.com",
  "hugh.pinfold@northkb.com",
  "grace.seeley@northkb.com",
  "nick@northasg.com",
  "tom.crosse@northkb.com",
  "uli.sommerlatt@northkb.com",
  "gabs@northasg.com",
  "leo@northasg.com",
  "jonty.norton@northkb.com",
  "jorn@northasg.com",
  "Barend@northasg.com",
  "richard.lott@northtechnologygroup.com",
  "sam@northasg.com",
  "klaus@northasg.com",
  "thies@northasg.com",
  "max@northasg.com",
  "jeroen@northasg.com",
  "mike.raper@northkb.com",
  "dave.little@northsails.com",
  "chris.williams@northsails.com",
  "Steve.calder@northsails",
];

const generateUsers = async () => {
  // const addPasswords = users.map
};

// Math.random().toString(36).substring(7);
